CREATE INDEX booking_id_idx ON ACCOUNT(BOOKING_BOOKING_ID);
CREATE INDEX customer_idx ON CUSTOMER(FIRST_NAME, LAST_NAME);
CREATE INDEX passport_idx ON CUSTOMER(PASSPORT_NUMBER);
CREATE INDEX hotel_idx ON HOTEL(NAME, ROOMS_COUNT);
CREATE INDEX city_id_idx ON HOTEL(CITY_CITY_ID);
CREATE INDEX manager_idx ON TOUR_MANAGER(FIRST_NAME, LAST_NAME);
CREATE INDEX tour_type_idx ON TOUR(TOUR_TYPE_TOUR_TYPE_ID);
CREATE INDEX duration_idx ON TOUR(NUMBER_OF_DAYS);